name: practica1
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  image_picker: ^0.6.3+44
  provider: ^4.0.4

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AmericanCaptain
      fonts:
        - asset: assets/fonts/AmericanCaptain/American-Captain.ttf
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel/Abel-Regular.ttf
    - family: GochiHand
      fonts:
        - asset: assets/fonts/GochiHand/GochiHand-Regular.ttf
    - family: Kalam
      fonts:
        - asset: assets/fonts/Kalam/Kalam-Regular.ttf
        - asset: assets/fonts/Kalam/Kalam-Light.ttf
          weight: 300
        - asset: assets/fonts/Kalam/Kalam-Bold.ttf
          weight: 700
    - family: Economica
      fonts:
        - asset: assets/fonts/Economica/Economica-Regular.ttf
        - asset: assets/fonts/Economica/Economica-Italic.ttf
          style: italic
        - asset: assets/fonts/Economica/Economica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Economica/Economica-BoldItalic.ttf
          style: italic
          weight: 700